name: 'open_metrics_project'
version: '1.0.0'
config-version: 2

profile: 'open_metrics'

require-dbt-version: [">=1.10.0", "<1.11.0"]

model-paths: ['models']
seed-paths: ['seeds']
test-paths: ['tests']
macro-paths: ['macros']

models:
  open_metrics_project:
    +schema: analytics
    staging:
      +materialized: view
    marts:
      +materialized: table

seeds:
  open_metrics_project:
    +schema: analytics_raw
