version: 2

models:
  - name: stg_olist__orders
    columns:
      - name: order_id
        tests: [not_null, unique]
      - name: customer_id
        tests: [not_null]
      - name: order_purchase_ts
        tests: [not_null]

  - name: stg_olist__order_items
    columns:
      - name: order_id
        tests: [not_null]
      - name: order_item_id
        tests: [not_null]
      - name: price
        tests: [not_null]

  - name: stg_olist__customers
    columns:
      - name: customer_id
        tests: [not_null, unique]

  - name: stg_olist__payments
    columns:
      - name: order_id
        tests: [not_null]
      - name: payment_value
        tests: [not_null]

  - name: stg_olist__reviews
    columns:
      - name: review_id
        tests: [not_null, unique]
      - name: order_id
        tests: [not_null]
      - name: review_score
        tests: [not_null]

  - name: stg_olist__products
    columns:
      - name: product_id
        tests: [not_null, unique]

  - name: stg_olist__sellers
    columns:
      - name: seller_id
        tests: [not_null, unique]
