version: 2

sources:
  - name: olist
    database: "{{ target.database }}"
    schema: "{{ target.schema }}"
    tables:
      - name: orders
        identifier: olist_orders_dataset
      - name: order_items
        identifier: olist_order_items_dataset
      - name: customers
        identifier: olist_customers_dataset
      - name: payments
        identifier: olist_order_payments_dataset
      - name: products
        identifier: olist_products_dataset
      - name: sellers
        identifier: olist_sellers_dataset
      - name: order_reviews
        identifier: olist_order_reviews_dataset
