open_metrics:
  target: dev
  outputs:
    dev:
      type: postgres
      host: 127.0.0.1
      port: 5433
      user: metabase
      password: analytics_pwd
      dbname: metabase
      schema: analytics
      threads: 4
      sslmode: disable

    ci:
      type: postgres
      host: 127.0.0.1
      port: 5432
      user: postgres
      password: postgres
      dbname: analytics
      schema: analytics
      threads: 4
      sslmode: disable