name: CI

on:
  push:
  pull_request:

jobs:
  lint-and-parse:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: analytics
        ports: ["5432:5432"]
        options: >-
          --health-cmd="pg_isready -U postgres -d analytics"
          --health-interval=10s --health-timeout=5s --health-retries=10

    env:
      DBT_PROFILES_DIR: ${{ github.workspace }}/profiles
      DBT_TARGET: ci

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps (dbt, sqlfluff, etc.)
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          dbt --version
          sqlfluff --version

      - name: Wait for Postgres
        run: |
          for i in {1..30}; do
            pg_isready -h 127.0.0.1 -p 5432 -U postgres -d analytics && exit 0
            sleep 2
          done
          echo "Postgres no respondió a tiempo"; exit 1
      
      - name: Force profiles.yml target=ci (CI only)
        run: |
          sed -i 's/^  target: dev/  target: ci/' profiles/profiles.yml
          echo "Using target:"; grep '^[ ]*target:' -n profiles/profiles.yml

      - name: dbt deps
        working-directory: ./dbt_project
        run: dbt deps

      - name: dbt parse (no DB writes)
        working-directory: ./dbt_project
        run: dbt parse

      - name: Lint SQL (SQLFluff)
        env:
          SQLFLUFF_DBT_PROFILES_DIR: ${{ github.workspace }}/profiles
          SQLFLUFF_DBT_PROFILE: open_metrics
          SQLFLUFF_DBT_TARGET_NAME: ci
        run: sqlfluff lint dbt_project --config ./.sqlfluff
