name: CI

on:
  push:
  pull_request:

jobs:
  lint-and-parse:
    runs-on: ubuntu-latest

    # Postgres efímero para que el templater de dbt no falle
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: analytics
        ports: ["5432:5432"]
        options: >-
          --health-cmd="pg_isready -U postgres -d analytics"
          --health-interval=10s --health-timeout=5s --health-retries=10

    env:
      # usa tu profiles/profiles.yml del repo
      DBT_PROFILES_DIR: ./profiles
      # fuerza a usar el target "ci" (sin tocar tu local)
      DBT_TARGET: ci

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps (dbt + sqlfluff)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Nos aseguramos de tener sqlfluff y templater (por si no están en requirements.txt)
          pip install "sqlfluff==3.*" "sqlfluff-templater-dbt==3.*"

      - name: Wait for Postgres
        run: |
          for i in {1..30}; do
            pg_isready -h 127.0.0.1 -p 5432 -U postgres -d analytics && exit 0
            sleep 2
          done
          echo "Postgres no respondió a tiempo"; exit 1

      - name: dbt deps
        working-directory: ./dbt_project
        run: dbt deps

      - name: dbt parse (no DB writes)
        working-directory: ./dbt_project
        run: dbt parse 

      - name: Lint SQL (SQLFluff)
        run: sqlfluff lint dbt_project --config ./.sqlfluff
